# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, vars, modulesPath, ... }:
let
  mkShareOption = name: mkOption {
    type = types.bool;
    default = false;
    description = "Enable network share for ${name}.";
  };
in
{
  options = {
    storagefs.share.vega_nfs = {
      enable = mkOption {
        type = types.bool;
        default = false;
      };
    };
  };
  config = mkIf (config.storagefs.share.vega_nfs.enable) {
    fileSystems."/home/${vars.user}/.share/vega_nfs" = {#truenas nfs storage
      device = "10.2.11.200:/mnt/vega/vega";
      fsType = "nfs";
      options = [ "x-systemd.automount" "noauto" "x-systemd.device-timeout=5s" "x-systemd.mount-timeout=5s"];
    };



  };
  # fileSystems."/home/${vars.user}/.share/vega" =
  #   { #truenas smb storage
  #     device = "//10.2.11.200/vega";
  #     fsType = "cifs";
  #     options = let
  #       automount_opts = "x-systemd.automount,user,soft,noauto,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
  #       # automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
  #     in ["${automount_opts},mfsymlinks,uid=1000,gid=1000,credentials=/home/${vars.user}/.share/creds/vega"];
  #   };
}
