networks:
  frontend:
    name: frontend
    ipam:
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"
  vlan11:
    name: vlan11
    driver: macvlan
    driver_opts:
      parent: enp6s18
    external: false
    ipam:
      config:
        - subnet: "10.2.11.0/24"
          gateway: "10.2.11.1"
          ip_range: "10.2.11.0/24"
services:
 portainer:
  image: portainer/portainer-ce:2.18.4
  container_name: portainer
  security_opt:
      - no-new-privileges:true
  user: 0:0
  restart: always
  ports:
   - 8000:8000
   - 9000:9000
   - 9443:9443
  volumes:
   - /usr/docker_config/portainer/data:/data
   - /var/run/docker.sock:/var/run/docker.sock
  networks:
    frontend:
        ipv4_address: "172.18.255.254"
    # vlan11: # TODO fix this in compose2nix not working
    #   ipv4_address: "10.2.11.199"

