# Auto-generated using compose2nix v0.1.9.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."portainer" = {
    image = "portainer/portainer-ce:2.18.4";
    volumes = [
      "/usr/docker_config/portainer/data:/data:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    ports = [
      "8000:8000/tcp"
      "9000:9000/tcp"
      "9443:9443/tcp"
    ];
    user = "0:0";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=portainer"
      "--network=frontend"
      "--network=vlan11"
      "--security-opt=no-new-privileges:true"
    ];
  };
  systemd.services."docker-portainer" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-frontend.service"
      "docker-network-vlan11.service"
    ];
    requires = [
      "docker-network-frontend.service"
      "docker-network-vlan11.service"
    ];
    partOf = [
      "docker-compose-portainer-root.target"
    ];
    wantedBy = [
      "docker-compose-portainer-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-frontend" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f frontend";
    };
    script = ''
      docker network inspect frontend || docker network create frontend --subnet=172.18.0.0/16 --gateway=172.18.0.1
    '';
    partOf = [ "docker-compose-portainer-root.target" ];
    wantedBy = [ "docker-compose-portainer-root.target" ];
  };
  systemd.services."docker-network-vlan11" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f vlan11";
    };
    script = ''
      docker network inspect vlan11 || docker network create vlan11 --driver=macvlan --opt=parent=eth0 --subnet=10.2.11.0/24 --ip-range=10.2.11.0/24 --gateway=10.2.11.1
    '';
    partOf = [ "docker-compose-portainer-root.target" ];
    wantedBy = [ "docker-compose-portainer-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-portainer-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
