networks:
  ##bridge:
    ##name: bridge
    ##external: true
  frontend:
    name: frontend
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
            #  vlan12:
            #    name: vlan12
            #    driver: macvlan
            #    external: false
            #    driver_opts:
            #      parent: eth1-secure
            #      #com.docker.network.bridge.name: eth1-secure
            #    ipam:
            #      config:
            #        - subnet: 10.2.12.0/24
            #          gateway: 10.2.12.1
  vlan11:
    name: vlan11
    driver: macvlan
    driver_opts:
      parent: enp6s18
    external: false
    ipam:
      config:
        - subnet: 10.2.11.0/24
          gateway: 10.2.11.1
          ip_range: 10.2.11.0/24
   ##external: true
services:
 portainer:
  image: portainer/portainer-ce:2.20.3
  container_name: portainer
  security_opt:
      - no-new-privileges:true
  user: 0:0
  restart: always
  ports:
   - 8000:8000
   - 9000:9000
   - 9443:9443
  volumes:
   - /usr/docker_config/portainer/data:/data
   - /var/run/docker.sock:/var/run/docker.sock
  labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.icylair.com`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.icylair.com`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=frontend"
  #network_mode: "bridge"
  networks:
    frontend:
        ipv4_address: 172.18.255.254
    vlan11:
      ipv4_address: 10.2.11.199

