logLevel: info
healthCheckTimeout: 600
startPort: 10002
globalTTL: 480

macros:
  "latest-llama": >
    /home/user/workspace/llama-swap/llama-swap/result/bin/llama-server
    --host 0.0.0.0
    --port ${PORT}
    --jinja
    --metrics

models:
  #Gemma4-31B:
  #  cmd: >
  #    ${latest-llama}
  #    -hf unsloth/gemma-4-31B-it-GGUF:UD-Q4_K_XL
  #    -c 20480
  #    --temp 1
  #    --top-p 0.95
  #    --top-k 64

  Gemma4-26B-A4B:
    capabilities:
      context: 20000
    cmd: >
      ${latest-llama}
      -hf unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_M
      -c 20000
      --temp 1
      --top-p 0.95
      --top-k 64
  Qwen3.6-27B-general:
    capabilities:
      context: 30000
    cmd: >
      ${latest-llama}
      -hf unsloth/Qwen3.6-27B-GGUF:Q4_K_M
      -c 30000
      --temp 1
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 0.0
      --repeat-penalty 1.0
  Qwen3.6-27B-coding:
    capabilities:
      context: 40000
    cmd: >
      ${latest-llama}
      -hf unsloth/Qwen3.6-27B-GGUF:Q4_K_M
      -c 40000
      --temp 0.6
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 0.0
      --repeat-penalty 1.0
  Qwen3.6-27B-Instruct:
    capabilities:
      context: 20000
    cmd: >
      ${latest-llama}
      -hf unsloth/Qwen3.6-27B-GGUF:Q4_K_M
      -c 20000
      --temp 0.7
      --top-p 0.80
      --top-k 20
      --min-p 0.0
      --presence-penalty 1.5
      --repeat-penalty 1.0
      --reasoning off
  Qwen3.6-27B-coding-ctx-big:
    capabilities:
      context: 60000
    cmd: >
      ${latest-llama}
      -hf unsloth/Qwen3.6-27B-GGUF:Q4_K_M
      -c 60000
      --temp 0.6
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 0.0
      --repeat-penalty 1.0
  Gemma-4-12B:
    capabilities:
      context: 60000
    cmd: >
      ${latest-llama}
      -hf unsloth/gemma-4-12B-it-qat-GGUF:UD-Q4_K_XL
      -c 60000
      --temp 1
      --top-p 0.95
      --top-k 64
      --min-p 0.0
      --presence-penalty 0.0
      --repeat-penalty 1.0
