logLevel: info
healthCheckTimeout: 600
startPort: 10003
globalTTL: 480

macros:
  "default-llama": >
    /run/current-system/sw/bin/llama-server
    --host 0.0.0.0
    --port ${PORT}
    --jinja
    --metrics
    --cache-type-k q8_0
    --cache-type-v q8_0
    --offline
    -ngl all
  "latest-llama": >
    /home/user/workspace/llama-swap/llama-swap/result/bin/llama-server
    --host 0.0.0.0
    --port ${PORT}
    --jinja
    --metrics
    --cache-type-k q8_0
    --cache-type-v q8_0
    --offline
    -ngl all

models:
  #Gemma4-31B:
  #  cmd: >
  #    ${latest-llama}
  #    -hf unsloth/gemma-4-31B-it-GGUF:UD-Q4_K_XL
  #    -c 20480
  #    --temp 1
  #    --top-p 0.95
  #    --top-k 64

  Gemma4-26B-A4B:
    capabilities:
      context: 20480
    cmd: >
      ${default-llama}
      -hf unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_M
      -c 20480
      --temp 1
      --top-p 0.95
      --top-k 64
  Qwen3.6-27B-general:
    capabilities:
      context: 30720
    cmd: >
      ${latest-llama}
      -hf unsloth/Qwen3.6-27B-GGUF:Q4_K_M
      -c 30720
      --temp 1
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 0.0
      --repeat-penalty 1.0
  Gemma4-12B:
    capabilities:
      context: 25600
    cmd: >
      ${default-llama}
      -hf unsloth/gemma-4-12B-it-qat-GGUF:UD-Q4_K_XL
      -c 25600
      --temp 1
      --top-p 0.95
      --top-k 64
      --min-p 0.0
      --presence-penalty 0.0
      --repeat-penalty 1.0
      --spec-type draft-mtp
      --spec-draft-n-max 3

  Qwen3.6-27B-Instruct:
    capabilities:
      context: 20480
    cmd: >
      ${latest-llama}
      -hf unsloth/Qwen3.6-27B-GGUF:Q4_K_M
      -c 20480
      --temp 0.7
      --top-p 0.80
      --top-k 20
      --min-p 0.0
      --presence-penalty 1.5
      --repeat-penalty 1.0
      --reasoning off
  Qwen3.6-27B-coding:
    capabilities:
      context: 40960
    cmd: >
      ${latest-llama}
      -hf unsloth/Qwen3.6-27B-GGUF:Q4_K_M
      -c 40960
      --temp 0.6
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 0.0
      --repeat-penalty 1.0
  Qwen3.6-27B-coding-ctx-big:
    capabilities:
      context: 92160
    cmd: >
      ${latest-llama}
      -hf unsloth/Qwen3.6-27B-GGUF:Q4_K_M
      -c 92160
      --temp 0.6
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 0.0
      --repeat-penalty 1.0

  Qwen3.8-27B-Instruct:
    capabilities:
      context: 20480
    cmd: >
      ${default-llama}
      -hf unsloth/Qwen3.8-27B-GGUF:Q4_K_M
      -c 20480
      --temp 0.7
      --top-p 0.80
      --top-k 20
      --min-p 0.0
      --presence_penalty 1.5
      --repeat-penalty 1.0
      --reasoning off
  # Qwen3.8-27B-coding:
  #   capabilities:
  #     context: 102400
  #   cmd: >
  #     ${latest-llama}
  #     -hf unsloth/Qwen3.8-27B-GGUF:IQ4_XS
  #     -c 102400
  #     --temp 1
  #     --top-p 0.95
  #     --top-k 20
  #     --min-p 0.0
  #     --presence_penalty 0.0
  #     --repeat-penalty 1.0
  #     --offline
  # Qwen3.8-27B-coding-ctx-big:
  #   capabilities:
  #     context: 122880
  #   cmd: >
  #     ${default-llama}
  #     -hf unsloth/Qwen3.8-27B-GGUF:IQ4_XS
  #     -c 122880
  #     --temp 1
  #     --top-p 0.95
  #     --top-k 20
  #     --min-p 0.0
  #     --presence_penalty 0.0
  #     --repeat-penalty 1.0
  Qwen3.8-coding-mtp:
    capabilities:
      context: 81920
    cmd: >
      ${latest-llama}
      -hf unsloth/Qwen3.8-27B-GGUF:IQ4_XS
      -c 81920
      --temp 1
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence_penalty 0.0
      --repeat-penalty 1.0
      --offline
      --spec-type draft-mtp --spec-draft-n-max 3
      --cache-type-k-draft q4_0 --cache-type-v-draft q4_0
  Qwen3.8-coding-mtp-big:
    capabilities:
      context: 143360
    cmd: >
      ${latest-llama}
      -hf unsloth/Qwen3.8-27B-GGUF:IQ4_XS
      -c 143360
      --temp 1
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence_penalty 0.0
      --repeat-penalty 1.0
      --offline
      --spec-type draft-mtp --spec-draft-n-max 3
      --cache-type-k-draft q4_0 --cache-type-v-draft q4_0
